alias ll="ls -lh --color --group-directories-first"
alias lla="ls -lah --color --group-directories-first"
alias ..="cd .."
alias lease="cat /var/lib/dhcp/dhcpd.leases"
alias mp="./manage.py"
alias rs="./manage.py runserver"
alias cel="celery worker -B -E -A"
alias ve=". env/bin/activate"
alias sai="sudo apt-get install"
alias sar="sudo apt-get remove"
alias greph="grep -r --include \*.h"
alias greppy="grep -r --include \*.py"
alias grepc="grep -r --include \*.c"
alias jl="JLinkExe"
alias jls="cat <(printf 'connect\n\nS\n\n') - | JLinkExe -selectemubysn 518002451"
alias ta="tmux attach -t"
alias logicex="sudo ./Logic -geometry 1900x1100+0+430"
alias debug="Ozone *.jdebug &"
alias disp10="export DISPLAY=localhost:10"
alias disp11="export DISPLAY=localhost:11"
alias disp12="export DISPLAY=localhost:12"
alias disp0="export DISPLAY=localhost:0"
alias ...="cd ../../../"
alias ....="cd ../../../../"
alias .....="cd ../../../../../"
alias ......="cd ../../../../../../"
alias .......="cd ../../../../../../../"
alias ........="cd ../../../../../../../../"
